### ISSUE TITLE
Can't select tables "Unable to load tables" errors

### ISSUE THREAD

**Issue by reubenvandeventer** [singer-io/tap-quickbase#21]
Having problems getting my quickbase app integrated to an S3 bucket.  Have gone through all the guides and tried searching help guides.  

1. Quickbase app authentication passed
2. S3 (target) authentication passed
3. When I go to select tables to replicate it error out with this:
"Unable to load tables. The credentials saved for this integration may not be correct. Re-enter them in your settings and Stitch will try to connect again."

**Comment by reubenvandeventer** [comment]
More digging, I've found that the connection to quickbase is not working.  I get the error message below; however, in my Quickbase app admin it says the token is active...

2018-11-14 19:59:38,900Z   main - INFO Running tap-quickbase version 2.0.2 and target-stitch version 1.8.1
2018-11-14 19:59:38,994Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-quickbase --config /tmp/tap_discover_config.json --discover
2018-11-14 19:59:39,203Z    tap - INFO API GET https://reubenvandeventer.quickbase.com/db/bn57ewgtr, {'act': 'API_GetSchema'}
2018-11-14 19:59:39,469Z    tap - CRITICAL Error response from Quick Base (Code 83): User token is invalid
2018-11-14 19:59:39,470Z    tap - Traceback (most recent call last):
2018-11-14 19:59:39,470Z    tap -   File "tap-env/bin/tap-quickbase", line 11, in <module>
2018-11-14 19:59:39,470Z    tap -     sys.exit(main())
2018-11-14 19:59:39,471Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 491, in main
2018-11-14 19:59:39,471Z    tap -     raise exc
2018-11-14 19:59:39,471Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 488, in main
2018-11-14 19:59:39,471Z    tap -     main_impl()
2018-11-14 19:59:39,471Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 478, in main_impl
2018-11-14 19:59:39,471Z    tap -     do_discover(conn)
2018-11-14 19:59:39,472Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 222, in do_discover
2018-11-14 19:59:39,472Z    tap -     discover_catalog(conn).dump()
2018-11-14 19:59:39,472Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/__init__.py", line 148, in discover_catalog
2018-11-14 19:59:39,472Z    tap -     for table in conn.get_tables():
2018-11-14 19:59:39,472Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/qbconn.py", line 90, in get_tables
2018-11-14 19:59:39,472Z    tap -     schema = self.request(params, self.appid)
2018-11-14 19:59:39,473Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_quickbase/qbconn.py", line 60, in request
2018-11-14 19:59:39,473Z    tap -     raise Exception("Error response from Quick Base (Code {}): {}".format(self.error_code, self.error))
2018-11-14 19:59:39,473Z    tap - Exception: Error response from Quick Base (Code 83): User token is invalid
2018-11-14 19:59:39,504Z   main - INFO Tap exited abnormally with status 1
2018-11-14 19:59:39,506Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "Error response from Quick Base (Code 83): User token is invalid".

![image](https://user-images.githubusercontent.com/14525228/48509160-4a6b2980-e81e-11e8-8ce3-4ebfdf3083eb.png)

![image](https://user-images.githubusercontent.com/14525228/48509171-53f49180-e81e-11e8-9bf9-98dc4c99692a.png)

**Comment by luandy64** [comment]
Hi @reubenvandeventer ,

Thanks for opening an issue! To start debugging this, how exactly did you install and run the tap?

**Comment by luandy64** [comment]
@reubenvandeventer I'm closing this for now. If you want to start working on this again, feel free to reopen it and we can look at it 👍
